<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

defined( 'ABSPATH' ) || exit;

remove_action( 'genesis_loop', 'genesis_do_loop' );
 
add_action( 'genesis_loop', 'dev_page_loop' );


function dev_page_loop() {
  $base_url = get_stylesheet_directory_uri();
  ?>
  <section class="section-404" style="">
    <div class="container">
      <div class="section-404__content">
        <div class="section-404__number">
          <img src="<?php echo $base_url; ?>/assets/images/illustration-404.png" alt="person" title="person" class="person-404">
          <p>404</p>
        </div>
        <p>This page does not exist or can’t be found. It might be an old link or maybe it moved. Don’t worry, let’s guide you back home.</p>
        <a href="<?php echo get_home_url(); ?>" class="button button-red" alt="Go Back To Home Page" title="Go Back To Home Page">Go Back To Home Page</a>
      </div>
    </div>
  </section>
  <?php
}


genesis();